name: SnowBall
api-version: 1.15
author: Raimin&Dixi
version: ${project.version}
main: com.raimin.snowball.Main
description: Plugin to guapo de snowball
#loadBefore: 
commands: 
    Comandoxd: {}
        #description: xdlol
        #usage: asñdklañ
